// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKxmq9FNyOuAMX0dRUS43xDXiEjxm2b7s',
    appId: '1:173240309150:web:eac4ae3473874718cd728f',
    messagingSenderId: '173240309150',
    projectId: 'sigindemo-552f4',
    authDomain: 'sigindemo-552f4.firebaseapp.com',
    databaseURL: 'https://sigindemo-552f4-default-rtdb.firebaseio.com',
    storageBucket: 'sigindemo-552f4.appspot.com',
    measurementId: 'G-J59KPYL99W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUGXqWoOYnKm5ujZe-suVcib3-f_w7xPk',
    appId: '1:173240309150:android:6448168decef9bf4cd728f',
    messagingSenderId: '173240309150',
    projectId: 'sigindemo-552f4',
    databaseURL: 'https://sigindemo-552f4-default-rtdb.firebaseio.com',
    storageBucket: 'sigindemo-552f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJW-uPuWGKJh13EEmhjDaZN1CgXGXG-iI',
    appId: '1:173240309150:ios:51a7b2da9f66760acd728f',
    messagingSenderId: '173240309150',
    projectId: 'sigindemo-552f4',
    databaseURL: 'https://sigindemo-552f4-default-rtdb.firebaseio.com',
    storageBucket: 'sigindemo-552f4.appspot.com',
    androidClientId: '173240309150-4n3srd71hcvo32b9vi3nn49ra26av3lu.apps.googleusercontent.com',
    iosClientId: '173240309150-v4b4n3klgnouos2eq0apqbko1ncg8o3c.apps.googleusercontent.com',
    iosBundleId: 'sad',
  );
}
